---
  - name: Install nginx
    sudo: yes
    apt:  pkg=nginx state=latest

  - name: Ensure nginx log directory exists
    file: dest=/var/log/nginx/symfony state=directory

  - name: Change default nginx site
    sudo: yes
    template: src=default.tpl dest=/etc/nginx/sites-available/default
    notify: restart nginx

  - name: Upload ez params
    copy: src=../templates/ez_params.d dest=/etc/nginx/ez_params.d owner=root group=root mode=0644
    notify: restart nginx
